### ISSUE TITLE
About "PojavLauncher is now legal in the eyes of Microsoft"

### ISSUE THREAD

**Issue by Seblor** [PojavLauncherTeam/pojavlauncherteam.github.io#133]
Hello, I was browsing the website and saw this in the LEGAL page:

> PojavLauncher is now legal in the eyes of Microsoft

Can you clarify what you mean by that? Some members of my community understand it as meaning that Microsoft endorses PojavLauncher.

**Comment by TheDudeThatHack** [comment]
It means that "theoretically" to use the app you need to have a Microsoft account that bought minecraft. 
Remember, "theoretically."

**Comment by Seblor** [comment]
That only clears the authentication part, but nothing is said about the EULA & reverse engineering regulation (among other things).

**Comment by artdeell** [comment]
We didn't reverse engineer minecraft to make Pojav

**Comment by Seblor** [comment]
So can you clarify what "PojavLauncher is now legal in the eyes of Microsoft" means ? Did you communicate with Microsoft about the legality of the project ?

**Comment by artdeell** [comment]
No, we did not. Going to ask the one who made the page about the title of it.

Still, why are you so interested in this?

**Comment by Seblor** [comment]
Besides personal curiosity, I'm an admin in Minecraft-France which is the largest french-speaking Discord server and one of the largest news website about Minecraft, so I would like to be able to safely inform the members of the community about the stance Microsoft has towards Pojav.

As I said in my original message, some members have understood it as Microsoft endorsing Pojav, thinking it an "official" project made by people in contact with Microsoft, quoting the phrase I quoted earlier.

**Comment by artdeell** [comment]
Oh no it's not official. We had MS contact us to remove offline mode from the launcher, and this page was created after that.

Damn, we really need to return the "About" page.

**Comment by crystall1nedev** [comment]
Microsoft does not endorse PojavLauncher. 

I am a team member (currently on a hiatus from development as I work out personal and team-related issues), and I was the one that was contacted by Microsoft in 2021 about the legality of PojavLauncher.

We made adjustments to ensure that PojavLauncher was compliant with their standards, and they began to ignore us from then on.

So, while they don't endorse the project, we're in good standing.

**Comment by Seblor** [comment]
Ah, thank you both for the information, I really appreciate it !

**Comment by Nucceteere** [comment]
Now I'm confused. You guys said offline mode was removed but isn't local accounts and offline mode the same?

**Comment by crystall1nedev** [comment]
Local mode was originally designed to act similar to PolyMC/Prism Launcher: the ability to create offline accounts stayed, but downloading the game from within the launcher would require a proper license (in today's terms, a Microsoft account that bought the game.) This is why we revamped offline as local - to make the distinction between the two and ease the transition on users.

This option gave everyone what they wanted - Microsoft wouldn't have the game pirated anymore, and PojavLauncher was still able to keep some offline functionality (since there are some ways of playing that require it).

Both the iOS and Android clients got this update, as it's a change we agreed on as a team in private channels. However, as of right now, the iOS port is the only one to still have it - the authentication was written by Duy and myself. However the Android side reverted to the old behavior after a refactor of the codebase.

The simple fact is that we're in good standing... *for now.* I only work on the iOS port, and have barely any Android development experience, so there isn't much I can do.
