### ISSUE TITLE
Why don't people put pojavlauncher on appstore

### ISSUE THREAD

**Issue by Namm205** [PojavLauncherTeam/pojavlauncherteam.github.io#84]
I think putting pojavlauncher on appsstore will make it easier for people to download it

**Comment by Bros112** [comment]
Pojavlauncher is on the Google play store for Android (even if it is behind on updates sometimes).
Pojavlauncher is unlikely to come to the apple app store because it likely doesn't fit to Apple's guidelines for apps because of it's nonstandard, prone to issues and developer focused nature.
I hope this helps

**Comment by GaucovyAero** [comment]
yeah, it does not fit apples guidelines, minecraft needs jit to run and apple does not allow that, also we would have to pay 100$/year to be on the app store, which we obviously dont have
